id: bot'o'lytics
displayName: Bot'o'lytics
description: |
  Analyze your traffic for bot traffic using data from APM.
install:
  primary:
    link:
      url: https://docs.newrelic.com/introduction-apm/
icon: logo.png
